### ISSUE TITLE
Blog link dead

### ISSUE THREAD

**Issue by willghatch** [noctuid/dotfiles#1]
The link to your blog in this repo's readme file is dead.  Probably because it's a github.io blog and you just changed your username.

As a general note I'm always happy when I see other people who actually care about bringing modality and keyboard usability to everything.  I note that you mention hand/wrist pain, and I recommend the ergodox keyboard -- I got one and my pains went away.  I also switched to a customized dvorak layout, but I find even with the layout a lot of typing on normal-shaped keyboards will bring some wrist pain back, so I feel the physical layout of the ergodox helped a lot more.

Also, thanks for making cool emacs packages.

**Comment by noctuid** [comment]
I didn't bother putting it back up since I still haven't decided whether I'm going to switch to org-page, upgrade to octopress 3, or do something else. It's back up for now.

I actually almost bought an ergodox when they were on massdrop a couple times, but I decided that it wasn't quite what I wanted. I bought a keyboardio model 01 during the kickstarter, but until I get that I'm using colemak with a hacky wide-mod on my laptop keyboard. At this point I'm most interested in keyboards for convenience, but I do still sometimes have pinky pain (due to a lack of thumb keys). It's not really that convenient to lug an external keyboard around though, so I'm hoping that sometime (far) into the future there might be decently designed laptop keyboards (or I'll just settle for a Japanese laptop).
