### ISSUE TITLE
Helm vs Ivy

### ISSUE THREAD

**Issue by rgrinberg** [noctuid/dotfiles#2]
Your vimmy emacs setup is very interesting to me. Would be great to hear more about it. In particular, it's not clear how you're choosing between helm and ivy. Am I correct to say that you use both? Why is that? Which one supports a more modal/evil UI better?

**Comment by noctuid** [comment]
Yeah I don't have my emacs config up because it's pretty messy, but there aren't too many interesting things I'm doing that aren't mentioned here or in the evil-guide repo.

As for ivy and helm, I generally prefer ivy now, but I use helm if there isn't an existing ivy alternative for something. I don't use too many of helm's advanced features, but I do like multiple/separated sources in a few cases (e.g. helm-aprops; I have a key for searching buffers, recentf, files in the current dir, and then with locate). I haven't kept up with ivy's developments, and I'm not a power user of either, so I'm proably not the best person to ask though.

As for modality, I've always [used hydra](https://noctuid.github.io/blog/2015/02/03/a-more-evil-helm/) to add it. While ivy now ships with such a hydra, you can also just copy one of the helm ones off of the hydra wiki into your config, so there's not much of a difference. I honestly don't use this functionality that often. Normally, I'll just narrow the search and hit enter. If I use the hydra, it's usually just to move up and down. I used to use `key-chord` to execute the hydra (as opposed to having to hit escape twice to exit ivy or helm), but with input lag, `key-chord` wrongly executes even when typing slowly, so I stopped using it. Now I'm giving up comma for the hydra, and I just use `quoted-insert` if I ever really need comma. I also kind of think that using a modifier could be more ideal here (if I had available thumb keys or a better dual-role program).

**Comment by rgrinberg** [comment]
Thanks for the detailed response. If ivy isn't more amendable to a modal workflow then I will stick with helm for now. Also, what about your IRC client choice? Emacs has a few options for this, why did you choose circe over the rest?

**Comment by noctuid** [comment]
I liked some of the circe packages ([circe-notifications](https://github.com/eqyiel/circe-notifications) and [helm-circe](https://github.com/lesharris/helm-circe)) and the fact that you can [use a function](https://github.com/jorgenschaefer/circe/wiki/Configuration#safer-password-management) instead of a plaintext password. The other big thing for me was support for sasl authentication (there is a patched version of erc with sasl support though).

That said, circe is missing quite a few features that ERC has (like no support for a lot of commands, e.g. `/list`).

**Comment by rgrinberg** [comment]
I see. Circe still looks attractive. Thank you for the great guides!
